USE [master]
GO
/****** Object:  Database [JobCandidateDB]    Script Date: 6/28/2024 8:03:50 PM ******/
CREATE DATABASE [JobCandidateDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'JobCandidateDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\JobCandidateDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'JobCandidateDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\JobCandidateDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [JobCandidateDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [JobCandidateDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [JobCandidateDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [JobCandidateDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [JobCandidateDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [JobCandidateDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [JobCandidateDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [JobCandidateDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [JobCandidateDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [JobCandidateDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [JobCandidateDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [JobCandidateDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [JobCandidateDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [JobCandidateDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [JobCandidateDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [JobCandidateDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [JobCandidateDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [JobCandidateDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [JobCandidateDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [JobCandidateDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [JobCandidateDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [JobCandidateDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [JobCandidateDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [JobCandidateDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [JobCandidateDB] SET RECOVERY FULL 
GO
ALTER DATABASE [JobCandidateDB] SET  MULTI_USER 
GO
ALTER DATABASE [JobCandidateDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [JobCandidateDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [JobCandidateDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [JobCandidateDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [JobCandidateDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [JobCandidateDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'JobCandidateDB', N'ON'
GO
ALTER DATABASE [JobCandidateDB] SET QUERY_STORE = OFF
GO
USE [JobCandidateDB]
GO
/****** Object:  User [sqluser]    Script Date: 6/28/2024 8:03:52 PM ******/
CREATE USER [sqluser] FOR LOGIN [sqluser] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [sqluser]
GO
ALTER ROLE [db_securityadmin] ADD MEMBER [sqluser]
GO
ALTER ROLE [db_ddladmin] ADD MEMBER [sqluser]
GO
/****** Object:  Table [dbo].[Candidates]    Script Date: 6/28/2024 8:03:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Candidates](
	[ID] [uniqueidentifier] NOT NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](250) NOT NULL,
	[PhoneNumber] [nvarchar](50) NULL,
	[LinkedInProfile] [nvarchar](50) NULL,
	[GithubProfile] [nvarchar](50) NULL,
	[PreferedTime] [time](7) NULL,
	[Comments] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Candidates] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Candidates_Email]    Script Date: 6/28/2024 8:03:52 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Candidates_Email] ON [dbo].[Candidates]
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [JobCandidateDB] SET  READ_WRITE 
GO
